"""initial

Revision ID: 421988d9fa13
Revises: 1e2189c322c1
Create Date: 2026-02-20 18:36:57.966974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421988d9fa13'
down_revision: Union[str, Sequence[str], None] = '1e2189c322c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'property', ['id'])
    op.create_unique_constraint(None, 'property', ['link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property', type_='unique')
    op.drop_constraint(None, 'property', type_='unique')
    # ### end Alembic commands ###
