"""initial

Revision ID: 99a2ec37afc3
Revises: 421988d9fa13
Create Date: 2026-02-21 03:16:39.020823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a2ec37afc3'
down_revision: Union[str, Sequence[str], None] = '421988d9fa13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('square_m', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'square_m')
    # ### end Alembic commands ###
