"""initial

Revision ID: e486945b52b6
Revises: 3aa18d7c2ecd
Create Date: 2026-02-20 18:33:28.647759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e486945b52b6'
down_revision: Union[str, Sequence[str], None] = '3aa18d7c2ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'property', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property', type_='unique')
    # ### end Alembic commands ###
